micronaut:
  application:
    name: micronaut-data-maven
  server:
    netty:
      access-logger:
        enabled: true
        logger-name: access-logger

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/sri
    driverClassName: org.postgresql.Driver
    username: nallani
    password: nallani
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true